[package]
name = "motoko-decimal"
version = "0.9.0"
description = "A fixed point Decimal type and arithmetic for Motoko."
repository = "https://github.com/DATHKA/motoko-decimal"
keywords = [ "utils", "types", "decimal", "math", "fixed-point" ]
license = "MIT"

[dependencies]
core = "1.0.0"
test = "2.1.1"